// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/v1/user.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{1}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

type LoginRequest struct {
	Uid                  uint64                `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Phone                string                `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string                `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string                `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Extra                map[string]*anypb.Any `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetExtra() map[string]*anypb.Any {
	if m != nil {
		return m.Extra
	}
	return nil
}

type UserInfo struct {
	Uid                  uint64                `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Phone                string                `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string                `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string                `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Extra                map[string]*anypb.Any `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetExtra() map[string]*anypb.Any {
	if m != nil {
		return m.Extra
	}
	return nil
}

type LoginReply struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string    `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{4}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetUserRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{5}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetUserReply struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserReply) Reset()         { *m = GetUserReply{} }
func (m *GetUserReply) String() string { return proto.CompactTextString(m) }
func (*GetUserReply) ProtoMessage()    {}
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{6}
}

func (m *GetUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReply.Unmarshal(m, b)
}
func (m *GetUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReply.Marshal(b, m, deterministic)
}
func (m *GetUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReply.Merge(m, src)
}
func (m *GetUserReply) XXX_Size() int {
	return xxx_messageInfo_GetUserReply.Size(m)
}
func (m *GetUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReply proto.InternalMessageInfo

func (m *GetUserReply) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserListRequest struct {
	UidList              []uint64 `protobuf:"varint,1,rep,packed,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListRequest) Reset()         { *m = GetUserListRequest{} }
func (m *GetUserListRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserListRequest) ProtoMessage()    {}
func (*GetUserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{7}
}

func (m *GetUserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListRequest.Unmarshal(m, b)
}
func (m *GetUserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListRequest.Marshal(b, m, deterministic)
}
func (m *GetUserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListRequest.Merge(m, src)
}
func (m *GetUserListRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserListRequest.Size(m)
}
func (m *GetUserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListRequest proto.InternalMessageInfo

func (m *GetUserListRequest) GetUidList() []uint64 {
	if m != nil {
		return m.UidList
	}
	return nil
}

type GetUserListReply struct {
	Users                []*UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetUserListReply) Reset()         { *m = GetUserListReply{} }
func (m *GetUserListReply) String() string { return proto.CompactTextString(m) }
func (*GetUserListReply) ProtoMessage()    {}
func (*GetUserListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{8}
}

func (m *GetUserListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListReply.Unmarshal(m, b)
}
func (m *GetUserListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListReply.Marshal(b, m, deterministic)
}
func (m *GetUserListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListReply.Merge(m, src)
}
func (m *GetUserListReply) XXX_Size() int {
	return xxx_messageInfo_GetUserListReply.Size(m)
}
func (m *GetUserListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListReply proto.InternalMessageInfo

func (m *GetUserListReply) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateRequest struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{9}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReply) Reset()         { *m = UpdateReply{} }
func (m *UpdateReply) String() string { return proto.CompactTextString(m) }
func (*UpdateReply) ProtoMessage()    {}
func (*UpdateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{10}
}

func (m *UpdateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReply.Unmarshal(m, b)
}
func (m *UpdateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReply.Marshal(b, m, deterministic)
}
func (m *UpdateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReply.Merge(m, src)
}
func (m *UpdateReply) XXX_Size() int {
	return xxx_messageInfo_UpdateReply.Size(m)
}
func (m *UpdateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "user.v1.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "user.v1.RegisterReply")
	proto.RegisterType((*LoginRequest)(nil), "user.v1.LoginRequest")
	proto.RegisterMapType((map[string]*anypb.Any)(nil), "user.v1.LoginRequest.ExtraEntry")
	proto.RegisterType((*UserInfo)(nil), "user.v1.UserInfo")
	proto.RegisterMapType((map[string]*anypb.Any)(nil), "user.v1.UserInfo.ExtraEntry")
	proto.RegisterType((*LoginReply)(nil), "user.v1.LoginReply")
	proto.RegisterType((*GetUserRequest)(nil), "user.v1.GetUserRequest")
	proto.RegisterType((*GetUserReply)(nil), "user.v1.GetUserReply")
	proto.RegisterType((*GetUserListRequest)(nil), "user.v1.GetUserListRequest")
	proto.RegisterType((*GetUserListReply)(nil), "user.v1.GetUserListReply")
	proto.RegisterType((*UpdateRequest)(nil), "user.v1.UpdateRequest")
	proto.RegisterType((*UpdateReply)(nil), "user.v1.UpdateReply")
}

func init() { proto.RegisterFile("user/v1/user.proto", fileDescriptor_6eeaf71090dd90b5) }

var fileDescriptor_6eeaf71090dd90b5 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcd, 0x6a, 0xdb, 0x4c,
	0x14, 0x45, 0x91, 0x14, 0xfb, 0xbb, 0xb2, 0x63, 0x67, 0x6c, 0x27, 0xb2, 0xbe, 0x2c, 0xcc, 0x40,
	0xa9, 0xf1, 0x42, 0xc2, 0x2e, 0x0d, 0xc5, 0x59, 0xb5, 0x10, 0xda, 0x40, 0x68, 0xa9, 0x20, 0x14,
	0xba, 0x68, 0x50, 0xf0, 0xc4, 0x15, 0x91, 0x35, 0xaa, 0x34, 0x72, 0xab, 0x6d, 0x5f, 0xa1, 0xcf,
	0xd1, 0xa7, 0xe9, 0x0b, 0x74, 0xd1, 0x07, 0xe8, 0x23, 0x94, 0x99, 0x91, 0x64, 0xf9, 0x27, 0x10,
	0x28, 0x74, 0x63, 0xcf, 0xdc, 0x73, 0xef, 0x39, 0xf7, 0x47, 0x77, 0x00, 0xa5, 0x09, 0x89, 0x9d,
	0xe5, 0xd8, 0xe1, 0xff, 0x76, 0x14, 0x53, 0x46, 0x51, 0x4d, 0x9c, 0x97, 0x63, 0xeb, 0x64, 0x4e,
	0xe9, 0x3c, 0x20, 0x8e, 0x17, 0xf9, 0x8e, 0x17, 0x86, 0x94, 0x79, 0xcc, 0xa7, 0x61, 0x22, 0xdd,
	0xac, 0x7e, 0x8e, 0x8a, 0xdb, 0x4d, 0x7a, 0xeb, 0x78, 0x61, 0x26, 0x21, 0xbc, 0x80, 0x96, 0x4b,
	0xe6, 0x7e, 0xc2, 0x48, 0xec, 0x92, 0x4f, 0x29, 0x49, 0x18, 0x42, 0xa0, 0x85, 0xde, 0x82, 0x98,
	0xca, 0x40, 0x19, 0xfe, 0xe7, 0x8a, 0x33, 0xea, 0x82, 0x1e, 0x7d, 0xa4, 0x21, 0x31, 0xf7, 0x84,
	0x51, 0x5e, 0x90, 0x05, 0xf5, 0xc8, 0x4b, 0x92, 0xcf, 0x34, 0x9e, 0x99, 0xaa, 0x00, 0xca, 0x3b,
	0x8f, 0x20, 0x0b, 0xcf, 0x0f, 0x4c, 0x4d, 0x46, 0x88, 0x0b, 0x6e, 0x41, 0x73, 0x25, 0x17, 0x05,
	0x19, 0xfe, 0xad, 0x40, 0xe3, 0x92, 0xce, 0xfd, 0xb0, 0x50, 0x6f, 0x83, 0x9a, 0xfa, 0x33, 0x21,
	0xae, 0xb9, 0xfc, 0x78, 0x8f, 0x76, 0xc9, 0xaf, 0x56, 0xf8, 0xd7, 0x32, 0xd2, 0x36, 0x32, 0x3a,
	0x05, 0x9d, 0x7c, 0x61, 0xb1, 0x67, 0xea, 0x03, 0x75, 0x68, 0x4c, 0x06, 0x76, 0xde, 0x3c, 0xbb,
	0xaa, 0x6f, 0x9f, 0x73, 0x97, 0xf3, 0x90, 0xc5, 0x99, 0x2b, 0xdd, 0xad, 0xd7, 0x00, 0x2b, 0x23,
	0xcf, 0xef, 0x8e, 0x64, 0x79, 0x73, 0xf8, 0x11, 0x8d, 0x40, 0x5f, 0x7a, 0x41, 0x2a, 0xf3, 0x33,
	0x26, 0x5d, 0x5b, 0x76, 0xdb, 0x2e, 0xba, 0x6d, 0x3f, 0x0f, 0x33, 0x57, 0xba, 0x4c, 0xf7, 0x9e,
	0x29, 0xf8, 0xa7, 0x02, 0xf5, 0xab, 0x84, 0xc4, 0x17, 0xe1, 0x2d, 0xfd, 0xcb, 0x72, 0x8b, 0x51,
	0x69, 0x95, 0x51, 0x4d, 0xd6, 0xcb, 0x3c, 0x29, 0xcb, 0x2c, 0x34, 0xff, 0x41, 0x89, 0x17, 0x00,
	0x79, 0x53, 0xa3, 0x20, 0x43, 0x8f, 0x40, 0xe3, 0x39, 0x08, 0x42, 0x63, 0x72, 0xb8, 0x95, 0x90,
	0x2b, 0x60, 0x5e, 0x22, 0xa3, 0x77, 0x24, 0x2c, 0x0a, 0x17, 0x17, 0x8c, 0xe1, 0xe0, 0x25, 0x61,
	0xdc, 0xf5, 0xde, 0x2f, 0x04, 0x3f, 0x85, 0x46, 0xe9, 0xf3, 0x70, 0x41, 0xec, 0x00, 0xca, 0xc3,
	0x2e, 0xfd, 0x84, 0x15, 0xf4, 0x7d, 0xa8, 0xa7, 0xfe, 0xec, 0x3a, 0xf0, 0x13, 0x66, 0x2a, 0x03,
	0x75, 0xa8, 0xb9, 0xb5, 0xd4, 0x9f, 0x71, 0x0f, 0x7c, 0x06, 0xed, 0xb5, 0x00, 0xae, 0xf5, 0x18,
	0x74, 0x4e, 0x96, 0x08, 0xdf, 0x9d, 0x62, 0x12, 0xc7, 0xa7, 0xd0, 0xbc, 0x8a, 0x66, 0x1e, 0x23,
	0x85, 0xd0, 0x03, 0xb3, 0x6c, 0x82, 0x51, 0xc4, 0x45, 0x41, 0x36, 0xf9, 0xae, 0x82, 0xc6, 0x3d,
	0xd0, 0x3b, 0xa8, 0x17, 0xab, 0x84, 0xcc, 0x32, 0x78, 0x63, 0x99, 0xad, 0xa3, 0x1d, 0x08, 0xdf,
	0xbb, 0xfe, 0xd7, 0x1f, 0xbf, 0xbe, 0xed, 0x75, 0xf0, 0x81, 0x78, 0x4e, 0x9c, 0x38, 0x07, 0xa7,
	0xca, 0x08, 0xbd, 0x02, 0x5d, 0x0c, 0x0f, 0xf5, 0x76, 0x6e, 0x88, 0xd5, 0xd9, 0x34, 0x73, 0xbe,
	0x8e, 0xe0, 0x6b, 0x22, 0x43, 0xf2, 0x05, 0x82, 0xe0, 0x2d, 0xd4, 0xf2, 0x7e, 0xa1, 0xe3, 0x32,
	0x68, 0x7d, 0x9a, 0x56, 0x6f, 0x1b, 0xe0, 0x7c, 0x47, 0x82, 0xaf, 0x8d, 0xf2, 0xfc, 0xe6, 0x84,
	0x5d, 0x8b, 0x8f, 0xe4, 0x03, 0x18, 0x95, 0x11, 0xa0, 0xff, 0x37, 0xa3, 0x2b, 0x93, 0xb4, 0xfa,
	0xbb, 0x41, 0x4e, 0x7f, 0x2c, 0xe8, 0x0f, 0x51, 0x4b, 0xd2, 0xf3, 0x1f, 0x31, 0x71, 0xf4, 0x06,
	0xf6, 0x65, 0xb7, 0xd1, 0xaa, 0x73, 0x6b, 0x63, 0xb3, 0xba, 0x5b, 0xf6, 0x0a, 0x21, 0x6e, 0xe4,
	0x84, 0x02, 0x9a, 0x2a, 0xa3, 0x17, 0xbd, 0xf7, 0x1d, 0x61, 0xe1, 0x2f, 0x73, 0xfe, 0x82, 0x9f,
	0x2d, 0xc7, 0x37, 0xfb, 0x62, 0x75, 0x9e, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x76, 0xf2,
	0xeb, 0xd6, 0x05, 0x00, 0x00,
}
